import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: process.env.NODE_ENV === "production" ? "Prod" : "Dev",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className} style={{
        margin: 0,
        padding: 0,
        fontWeight: 400,
        fontSize: 16,
        lineHeight: 1.5,
        color: "#333",
        minHeight: "100vh",
      }}>{children}</body>
    </html>
  );
}
